CREATE TABLE "agent_meta" (
  "agent_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agent_name" varchar(255) NOT NULL,
  "agent_load" varchar(255) NOT NULL,
  "agent_desc" text,
  "agent_url" varchar(500) NOT NULL,
  "side" varchar(50) NOT NULL,
  "param_schema" json NOT NULL,
  "supported_env_templates" varchar(500),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "env_template" (
  "template_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "template_name" varchar(255) UNIQUE NOT NULL,
  "template_desc" text,
  "param_schema" json NOT NULL,
  "static_config" json,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "environment" (
  "env_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "env_name" varchar(255) NOT NULL,
  "template_id" integer NOT NULL,
  "env_params" json NOT NULL,
  "status" varchar(20) DEFAULT 'unknown',
  "last_check_time" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "execution_plan" (
  "plan_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "plan_name" varchar(255) NOT NULL,
  "plan_desc" text,
  "camp" varchar(100),
  "env_template_id" integer NOT NULL,
  "plan_config" json NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "execution_record" (
  "deduce_id" bigint PRIMARY KEY,
  "plan_id" integer NOT NULL,
  "env_id" integer NOT NULL,
  "status" varchar(20) DEFAULT 'pending',
  "start_time" timestamp,
  "end_time" timestamp,
  "error_message" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "agent_execution_status" (
  "task_id" varchar(255) PRIMARY KEY,
  "deduce_id" bigint NOT NULL,
  "agent_id" integer NOT NULL,
  "agent_status" varchar(30) DEFAULT 'not-started',
  "agent_params" json,
  "start_time" timestamp,
  "end_time" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "execution_log" (
  "log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "deduce_id" bigint NOT NULL,
  "task_id" varchar(255),
  "log_level" varchar(20) DEFAULT 'info',
  "log_content" text NOT NULL,
  "log_timestamp" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now())
);

CREATE INDEX "idx_agent_name" ON "agent_meta" ("agent_name");

CREATE INDEX "idx_agent_side" ON "agent_meta" ("side");

CREATE INDEX "idx_env_template" ON "environment" ("template_id");

CREATE INDEX "idx_env_status" ON "environment" ("status");

CREATE INDEX "idx_env_template_status" ON "environment" ("template_id", "status");

CREATE INDEX "idx_plan_env_template" ON "execution_plan" ("env_template_id");

CREATE INDEX "idx_plan_camp" ON "execution_plan" ("camp");

CREATE INDEX "idx_plan_env_camp" ON "execution_plan" ("env_template_id", "camp");

CREATE INDEX "idx_record_plan" ON "execution_record" ("plan_id");

CREATE INDEX "idx_record_env" ON "execution_record" ("env_id");

CREATE INDEX "idx_record_status" ON "execution_record" ("status");

CREATE INDEX "idx_record_plan_time" ON "execution_record" ("plan_id", "created_at");

CREATE INDEX "idx_record_status_time" ON "execution_record" ("status", "created_at");

CREATE INDEX "idx_agent_deduce" ON "agent_execution_status" ("deduce_id");

CREATE INDEX "idx_agent_meta" ON "agent_execution_status" ("agent_id");

CREATE INDEX "idx_agent_status" ON "agent_execution_status" ("agent_status");

CREATE INDEX "idx_agent_deduce_time" ON "agent_execution_status" ("deduce_id", "created_at");

CREATE INDEX "idx_log_deduce" ON "execution_log" ("deduce_id");

CREATE INDEX "idx_log_task" ON "execution_log" ("task_id");

CREATE INDEX "idx_log_level" ON "execution_log" ("log_level");

CREATE INDEX "idx_log_deduce_time" ON "execution_log" ("deduce_id", "log_timestamp");

CREATE INDEX "idx_log_task_time" ON "execution_log" ("task_id", "log_timestamp");

COMMENT ON TABLE "agent_meta" IS '存储智能体元数据和参数声明，对应前端 Agent 类型';

COMMENT ON COLUMN "agent_meta"."agent_id" IS '智能体ID（自增主键）';

COMMENT ON COLUMN "agent_meta"."agent_name" IS '智能体名称';

COMMENT ON COLUMN "agent_meta"."agent_load" IS '智能体加载路径（如：AgentExample）';

COMMENT ON COLUMN "agent_meta"."agent_desc" IS '智能体描述';

COMMENT ON COLUMN "agent_meta"."agent_url" IS 'zip包存储路径（文件系统路径或对象存储URL）';

COMMENT ON COLUMN "agent_meta"."side" IS '阵营信息（如：red/blue/neutral）';

COMMENT ON COLUMN "agent_meta"."param_schema" IS 'config.yaml参数声明（AgentParam[]）';

COMMENT ON COLUMN "agent_meta"."supported_env_templates" IS '支持的环境类型ID列表，逗号分隔（如：''1,2,3''）';

COMMENT ON COLUMN "agent_meta"."created_at" IS '创建时间';

COMMENT ON COLUMN "agent_meta"."updated_at" IS '更新时间';

COMMENT ON TABLE "env_template" IS '环境类型模板定义，对应前端 config.yaml 中的 envs 配置';

COMMENT ON COLUMN "env_template"."template_id" IS '模板ID（自增主键）';

COMMENT ON COLUMN "env_template"."template_name" IS '模板名称（如：''lt'', ''pysim''）';

COMMENT ON COLUMN "env_template"."template_desc" IS '模板描述';

COMMENT ON COLUMN "env_template"."param_schema" IS '动态参数声明（用户可配置的参数，对应前端 dynamic 配置）';

COMMENT ON COLUMN "env_template"."static_config" IS '静态配置（bizValue等固定配置，对应前端 static 配置）';

COMMENT ON COLUMN "env_template"."created_at" IS '创建时间';

COMMENT ON COLUMN "env_template"."updated_at" IS '更新时间';

COMMENT ON TABLE "environment" IS '环境配置实例，对应前端 EnvConfig（但不含 dispatchedAgents）';

COMMENT ON COLUMN "environment"."env_id" IS '环境ID（自增主键）';

COMMENT ON COLUMN "environment"."env_name" IS '环境实例名称';

COMMENT ON COLUMN "environment"."template_id" IS '关联的环境模板';

COMMENT ON COLUMN "environment"."env_params" IS '配置的参数值（用户填写的动态参数）';

COMMENT ON COLUMN "environment"."status" IS '环境状态：available/unavailable/unknown';

COMMENT ON COLUMN "environment"."last_check_time" IS '最后连接测试时间';

COMMENT ON COLUMN "environment"."created_at" IS '创建时间';

COMMENT ON COLUMN "environment"."updated_at" IS '更新时间';

COMMENT ON TABLE "execution_plan" IS '执行方案模板，可重复执行。对应前端保存的方案配置（不含运行状态）';

COMMENT ON COLUMN "execution_plan"."plan_id" IS '方案ID（自增主键）';

COMMENT ON COLUMN "execution_plan"."plan_name" IS '方案名称';

COMMENT ON COLUMN "execution_plan"."plan_desc" IS '方案描述';

COMMENT ON COLUMN "execution_plan"."camp" IS '阵营（如：red/blue）';

COMMENT ON COLUMN "execution_plan"."env_template_id" IS '关联的环境类型';

COMMENT ON COLUMN "execution_plan"."plan_config" IS '方案配置（智能体列表、顺序、参数等，不含执行状态）';

COMMENT ON COLUMN "execution_plan"."created_at" IS '创建时间';

COMMENT ON COLUMN "execution_plan"."updated_at" IS '更新时间';

COMMENT ON TABLE "execution_record" IS '执行记录表，每次执行创建一条记录。deduce_id 作为主键，前端在执行前生成';

COMMENT ON COLUMN "execution_record"."deduce_id" IS '执行唯一标识（Snowflake ID，主键，前端生成）';

COMMENT ON COLUMN "execution_record"."plan_id" IS '关联的执行方案';

COMMENT ON COLUMN "execution_record"."env_id" IS '使用的环境实例';

COMMENT ON COLUMN "execution_record"."status" IS '执行状态：pending/running/completed/failed/cancelled/stopped';

COMMENT ON COLUMN "execution_record"."start_time" IS '执行开始时间';

COMMENT ON COLUMN "execution_record"."end_time" IS '执行结束时间';

COMMENT ON COLUMN "execution_record"."error_message" IS '错误信息（状态为 failed 时记录）';

COMMENT ON COLUMN "execution_record"."created_at" IS '记录创建时间';

COMMENT ON COLUMN "execution_record"."updated_at" IS '记录更新时间';

COMMENT ON TABLE "agent_execution_status" IS '智能体执行状态表，对应前端 DispatchedAgent。task_id 作为主键，前端生成';

COMMENT ON COLUMN "agent_execution_status"."task_id" IS '智能体任务ID（Snowflake ID，主键，前端生成）';

COMMENT ON COLUMN "agent_execution_status"."deduce_id" IS '关联的执行记录';

COMMENT ON COLUMN "agent_execution_status"."agent_id" IS '关联的智能体元数据';

COMMENT ON COLUMN "agent_execution_status"."agent_status" IS '智能体状态：not-started/ready/pending/running/stopping/ended/error/manually-stopped/unknown';

COMMENT ON COLUMN "agent_execution_status"."agent_params" IS '执行时使用的参数（当前参数值）';

COMMENT ON COLUMN "agent_execution_status"."start_time" IS '智能体开始时间';

COMMENT ON COLUMN "agent_execution_status"."end_time" IS '智能体结束时间';

COMMENT ON COLUMN "agent_execution_status"."created_at" IS '记录创建时间';

COMMENT ON COLUMN "agent_execution_status"."updated_at" IS '记录更新时间';

COMMENT ON TABLE "execution_log" IS '执行日志表，区分方案级日志（task_id为空）和智能体级日志（task_id非空）';

COMMENT ON COLUMN "execution_log"."log_id" IS '日志ID（自增主键）';

COMMENT ON COLUMN "execution_log"."deduce_id" IS '关联的执行记录';

COMMENT ON COLUMN "execution_log"."task_id" IS '关联的智能体任务（可为空，表示方案级日志）';

COMMENT ON COLUMN "execution_log"."log_level" IS '日志级别：debug/info/warning/error';

COMMENT ON COLUMN "execution_log"."log_content" IS '日志内容';

COMMENT ON COLUMN "execution_log"."log_timestamp" IS '日志产生时间';

COMMENT ON COLUMN "execution_log"."created_at" IS '日志入库时间';

ALTER TABLE "execution_plan" ADD FOREIGN KEY ("env_template_id") REFERENCES "env_template" ("template_id");

ALTER TABLE "environment" ADD FOREIGN KEY ("template_id") REFERENCES "env_template" ("template_id");

ALTER TABLE "execution_record" ADD FOREIGN KEY ("plan_id") REFERENCES "execution_plan" ("plan_id");

ALTER TABLE "execution_record" ADD FOREIGN KEY ("env_id") REFERENCES "environment" ("env_id");

ALTER TABLE "agent_execution_status" ADD FOREIGN KEY ("deduce_id") REFERENCES "execution_record" ("deduce_id");

ALTER TABLE "agent_execution_status" ADD FOREIGN KEY ("agent_id") REFERENCES "agent_meta" ("agent_id");

ALTER TABLE "execution_log" ADD FOREIGN KEY ("deduce_id") REFERENCES "execution_record" ("deduce_id");

ALTER TABLE "execution_log" ADD FOREIGN KEY ("task_id") REFERENCES "agent_execution_status" ("task_id");
